/* Reading bytes as text, which is the cost Go hides inside a range loop.
 *
 * Every row here has a Go row next to it, and for once that is the whole
 * comparison rather than a formality, because unicode/utf8 is pure computation
 * over a byte slice with no allocator, no interface and no runtime underneath
 * it. If burrow is slower than Go on any of these, it is slower at the same
 * table lookups and the same compares, and that is a number somebody has to
 * explain.
 *
 * Three input shapes, because a decoder behaves completely differently across
 * them. ASCII takes the one byte path on every character and never touches the
 * table. Japanese takes the three byte path on every character and touches it
 * every time. Mixed is what real text looks like, and it is the one where
 * branch prediction has something to get wrong.
 *
 * The naive rows are the honest baseline for the counting and validating
 * benchmarks. Counting runes in ASCII is a byte loop if you already know the
 * input is ASCII, and the point of measuring both is to say what the general
 * version costs you when the specific one would have done.
 *
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "bench.h"

#include "burrow/core.h"
#include "burrow/slice.h"
#include "burrow/type.h"
#include "burrow/utf8.h"

#include <string.h>

/* Ten characters each, so the two rows are directly comparable: same number of
 * runes, three times the bytes. */
static const char ascii10_c[] = "0123456789";
static const char japanese10_c[] = "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e"
                                   "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e"
                                   "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e"
                                   "\xe6\x97\xa5";

/* A line of real text with accents in it, which is the shape almost all text
 * actually has: mostly ASCII, with something wider every few words. */
static const char mixed_c[] = "the na\xc3\xafve caf\xc3\xa9 r\xc3\xb4le of "
                              "co\xc3\xb6rdination, said the \xe2\x9c\x93 sign";

#define LONG_LEN 4096
static char long_ascii[LONG_LEN + 1];

static void fill_long(void) {
    if (long_ascii[0] != '\0')
        return;
    for (int i = 0; i < LONG_LEN; i++)
        long_ascii[i] = (char)('0' + (i % 10));
}

static Str ascii10(void) {
    Str s = {(const Byte *)ascii10_c, (Int)(sizeof ascii10_c - 1)};
    return s;
}

static Str japanese10(void) {
    Str s = {(const Byte *)japanese10_c, (Int)(sizeof japanese10_c - 1)};
    return s;
}

static Str mixed(void) {
    Str s = {(const Byte *)mixed_c, (Int)(sizeof mixed_c - 1)};
    return s;
}

static Str long_str(void) {
    Str s;
    fill_long();
    s.p = (const Byte *)long_ascii;
    s.len = LONG_LEN;
    return s;
}

/* ------------------------------------------------------------------ decoding
 *
 * One rune out of the front of a string, which is the operation every other
 * function here is built out of. The ASCII row should be a compare and a load.
 * The Japanese row is the table lookup plus two range checks. */

BENCH(utf8_decode_ascii) {
    Str s = ascii10();

    BENCH_LOOP(b) {
        Int size;
        bench_keep_u64((uint64_t)utf8_decode_rune_in_string(s, &size));
    }
}

BENCH(utf8_decode_japanese) {
    Str s = japanese10();

    BENCH_LOOP(b) {
        Int size;
        bench_keep_u64((uint64_t)utf8_decode_rune_in_string(s, &size));
    }
}

/* The same call through the byte slice spelling. Both go to the same internal
 * function over a pointer and a length, so this row exists to prove that the
 * Slice header costs nothing extra on the way in. */
BENCH(utf8_decode_slice) {
    Str s = japanese10();
    Slice p = slice_from((void *)(size_t)s.p, s.len, s.len, TYPE_BYTE);

    BENCH_LOOP(b) {
        Int size;
        bench_keep_u64((uint64_t)utf8_decode_rune(p, &size));
    }
}

/* ---------------------------------------------------------------- the loop
 *
 * str_runes and str_next_rune, which is Go's for i, r := range s and is the
 * thing most programs actually use. The comparison against Go here is the one
 * that matters most in this file, because Go's version is generated by the
 * compiler rather than called, and a function call per rune is the obvious way
 * for a C port to lose. These two rows are what caught burrow doing exactly
 * that, and they are the reason the iterator is inline now. */

BENCH(utf8_range_mixed) {
    Str s = mixed();

    BENCH_LOOP(b) {
        Int total = 0;
        Int i;
        Rune r;
        for (StrIter it = str_runes(s); str_next_rune(&it, &i, &r);)
            total += (Int)r;
        bench_keep_u64((uint64_t)total);
    }
}

BENCH(utf8_range_ascii) {
    Str s = ascii10();

    BENCH_LOOP(b) {
        Int total = 0;
        Rune r;
        for (StrIter it = str_runes(s); str_next_rune(&it, NULL, &r);)
            total += (Int)r;
        bench_keep_u64((uint64_t)total);
    }
}

/* The same sum written as a byte loop, which is what you should write when you
 * know the input is ASCII. The gap between this and the row above is what the
 * decode costs you on input that did not need decoding, and it is the number
 * behind the advice in the guide. */
BENCH(utf8_range_ascii_raw) {
    Str s = ascii10();

    BENCH_LOOP(b) {
        Int total = 0;
        for (Int i = 0; i < s.len; i++)
            total += (Int)s.p[i];
        bench_keep_u64((uint64_t)total);
    }
}

/* ------------------------------------------------------------------ counting */

BENCH(utf8_rune_count_ascii) {
    Str s = ascii10();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_rune_count_in_string(s));
    }
}

BENCH(utf8_rune_count_japanese) {
    Str s = japanese10();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_rune_count_in_string(s));
    }
}

BENCH(utf8_rune_count_long) {
    Str s = long_str();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_rune_count_in_string(s));
    }
}

/* Counting bytes, which is what counting runes degenerates to when the input is
 * ASCII and you know it. 4096 iterations of a compare against 4096 iterations
 * of a compare and an add, so these two should be close. */
BENCH(utf8_rune_count_long_raw) {
    Str s = long_str();

    BENCH_LOOP(b) {
        Int n = 0;
        for (Int i = 0; i < s.len; i++)
            if ((s.p[i] & 0xC0) != 0x80)
                n++;
        bench_keep_u64((uint64_t)n);
    }
}

/* ----------------------------------------------------------------- validating
 *
 * The check you run once on bytes that came from outside the program. The long
 * ASCII row is the one to watch, because on four kilobytes of ASCII the answer
 * is decided entirely by whether the implementation goes through a run of it a
 * machine word at a time or a byte at a time. Both do now. That row is how the
 * one that does not gets found. */

BENCH(utf8_valid_ascii) {
    Str s = ascii10();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_valid_string(s));
    }
}

BENCH(utf8_valid_japanese) {
    Str s = japanese10();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_valid_string(s));
    }
}

BENCH(utf8_valid_long) {
    Str s = long_str();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_valid_string(s));
    }
}

BENCH(utf8_valid_mixed) {
    Str s = mixed();

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_valid_string(s));
    }
}

/* ------------------------------------------------------------------ encoding */

BENCH(utf8_encode_ascii) {
    Byte buf[8];
    Slice out = slice_from(buf, (Int)sizeof buf, (Int)sizeof buf, TYPE_BYTE);

    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_encode_rune(out, (Rune)('a' + (bench_i_ & 15))));
    }
}

BENCH(utf8_encode_wide) {
    Byte buf[8];
    Slice out = slice_from(buf, (Int)sizeof buf, (Int)sizeof buf, TYPE_BYTE);

    BENCH_LOOP(b) {
        bench_keep_u64(
            (uint64_t)utf8_encode_rune(out, (Rune)(0x1F300 + (bench_i_ & 15))));
    }
}

BENCH(utf8_rune_len) {
    BENCH_LOOP(b) {
        bench_keep_u64((uint64_t)utf8_rune_len((Rune)(0x1F300 + (bench_i_ & 15))));
    }
}

void register_utf8_benchmarks(void);

void register_utf8_benchmarks(void) {
    BENCH_RUN(utf8_decode_ascii);
    BENCH_RUN(utf8_decode_japanese);
    BENCH_RUN(utf8_decode_slice);
    BENCH_RUN(utf8_range_mixed);
    BENCH_RUN(utf8_range_ascii);
    BENCH_RUN(utf8_range_ascii_raw);
    BENCH_RUN(utf8_rune_count_ascii);
    BENCH_RUN(utf8_rune_count_japanese);
    BENCH_RUN(utf8_rune_count_long);
    BENCH_RUN(utf8_rune_count_long_raw);
    BENCH_RUN(utf8_valid_ascii);
    BENCH_RUN(utf8_valid_japanese);
    BENCH_RUN(utf8_valid_long);
    BENCH_RUN(utf8_valid_mixed);
    BENCH_RUN(utf8_encode_ascii);
    BENCH_RUN(utf8_encode_wide);
    BENCH_RUN(utf8_rune_len);
}
