// The Go side of the UTF-8 benchmarks.
//
// This is the fairest comparison in the suite. unicode/utf8 is pure computation
// over a byte slice, with no allocator, no interface dispatch and no runtime
// underneath it, so the two implementations are doing the same table lookups
// and the same compares on the same bytes. A gap here is burrow's to explain.
//
// One row looks like it is not a fair fight and it is the interesting one. Go's
// range loop is generated by the compiler, inline, with no call per rune, and a
// C port that spells the same loop out of two functions has an obvious way to
// lose. RangeMixed against utf8_range_mixed is the row worth reading first, and
// it is the row that made burrow change.
//
// ValidLong is the other one to read. Both sides skip a machine word at a time
// through a run of ASCII, so it is measuring the same idea written twice.
//
// Copyright 2026 The burrow Authors. All rights reserved.
// Use of this source code is governed by a BSD-style licence that can be found
// in the LICENSE file.

package bench

import (
	"testing"
	"unicode/utf8"
)

// Ten characters each, so the two are directly comparable: same runes, three
// times the bytes.
const (
	ascii10     = "0123456789"
	japanese10  = "日本語日本語日本語日"
	mixedString = "the naïve café rôle of coördination, said the ✓ sign"
)

const utf8LongLen = 4096

var longASCII string

func init() {
	buf := make([]byte, utf8LongLen)
	for i := range buf {
		buf[i] = byte('0' + i%10)
	}
	longASCII = string(buf)
}

// ------------------------------------------------------------------ decoding

func BenchmarkUtf8DecodeASCII(b *testing.B) {
	s := ascii10
	for i := 0; i < b.N; i++ {
		r, _ := utf8.DecodeRuneInString(s)
		sinkInt = int(r)
	}
}

func BenchmarkUtf8DecodeJapanese(b *testing.B) {
	s := japanese10
	for i := 0; i < b.N; i++ {
		r, _ := utf8.DecodeRuneInString(s)
		sinkInt = int(r)
	}
}

func BenchmarkUtf8DecodeSlice(b *testing.B) {
	p := []byte(japanese10)
	for i := 0; i < b.N; i++ {
		r, _ := utf8.DecodeRune(p)
		sinkInt = int(r)
	}
}

// ---------------------------------------------------------------- the loop
//
// The compiler generates this one inline, which is exactly why it is here.

func BenchmarkUtf8RangeMixed(b *testing.B) {
	s := mixedString
	for i := 0; i < b.N; i++ {
		total := 0
		for _, r := range s {
			total += int(r)
		}
		sinkInt = total
	}
}

func BenchmarkUtf8RangeASCII(b *testing.B) {
	s := ascii10
	for i := 0; i < b.N; i++ {
		total := 0
		for _, r := range s {
			total += int(r)
		}
		sinkInt = total
	}
}

// ------------------------------------------------------------------ counting

func BenchmarkUtf8RuneCountASCII(b *testing.B) {
	s := ascii10
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.RuneCountInString(s)
	}
}

func BenchmarkUtf8RuneCountJapanese(b *testing.B) {
	s := japanese10
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.RuneCountInString(s)
	}
}

func BenchmarkUtf8RuneCountLong(b *testing.B) {
	s := longASCII
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.RuneCountInString(s)
	}
}

// ----------------------------------------------------------------- validating

func BenchmarkUtf8ValidASCII(b *testing.B) {
	s := ascii10
	for i := 0; i < b.N; i++ {
		sinkB = utf8.ValidString(s)
	}
}

func BenchmarkUtf8ValidJapanese(b *testing.B) {
	s := japanese10
	for i := 0; i < b.N; i++ {
		sinkB = utf8.ValidString(s)
	}
}

// The word at a time ASCII skip is the whole of this one on both sides.
func BenchmarkUtf8ValidLong(b *testing.B) {
	s := longASCII
	for i := 0; i < b.N; i++ {
		sinkB = utf8.ValidString(s)
	}
}

func BenchmarkUtf8ValidMixed(b *testing.B) {
	s := mixedString
	for i := 0; i < b.N; i++ {
		sinkB = utf8.ValidString(s)
	}
}

// ------------------------------------------------------------------ encoding

func BenchmarkUtf8EncodeASCII(b *testing.B) {
	buf := make([]byte, 8)
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.EncodeRune(buf, rune('a'+(i&15)))
	}
}

func BenchmarkUtf8EncodeWide(b *testing.B) {
	buf := make([]byte, 8)
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.EncodeRune(buf, rune(0x1F300+(i&15)))
	}
}

func BenchmarkUtf8RuneLen(b *testing.B) {
	for i := 0; i < b.N; i++ {
		sinkInt = utf8.RuneLen(rune(0x1F300 + (i & 15)))
	}
}
